development: &defaults
  adapter: postgresql
  encoding: unicode
  database: receipts_dev
  pool: 2
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *defaults
  database: receipts_test

production:
  <<: *defaults
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
